### ISSUE TITLE
Charity

### ISSUE THREAD

**Issue by dferber90** [pybee/paying-the-piper#39] opened 2015-10-22 06:50 UTC
I've been carrying this idea with me for a bit, but it's in a very early stage.
Would love to hear thoughts and doubts on this.
### What if someone started a charity for OSS developers?

> If you are in the 33% tax bracket, the actual cost of a $100 donation is only $67 ($100 less the $33 tax savings) [[1](https://www.charitynavigator.org/index.cfm?bay=content.view&cpid=31)]

Donating to a charity will get the company tax benefits. This enables them to give more.

The charity would get its money by collecting donations from companies (and maybe individuals). The charity would then forward the donations to OS developers selected beforehand. Developers can get into this program by applying, so only a few selected projects are supported directly. Developers are only supported for a duration chosen upfront, to enable support of many projects. 

To keep the charity running, a percentage of the donations would have to be kept in. This money will be used to look for more donors, review which projects to support and so on.
#### Further possibilities:
- Hiring in tech is hard and companies go to great length to find talent. The README's of popular GitHub repositories and their websites are viewed countless times by the targeted audience. To further give back to the donors, a "Company X is using (and supporting) this project, and they're hiring" could be embedded. This would be a [Sponsorship Payment](https://www.gov.uk/tax-limited-company-gives-to-charity/sponsoring-a-charity), which is still deductible.
- Donors may influence which project their donation should count towards
- Micro donations to get some bug fixed or feature done in a specific project that is blocking the company
- PR: Let company use the charity's logo in their printed material, and link to them from the charity's website
#### Benefits:
- Developers can actually work on the OS project instead of spending their time doing something else, like writing a book about it or contract work
- Companies get tax benefits
- Companies may find new employees
- Companies can improve their image
#### Related:
- https://www.patreon.com/
- https://stripe.com/blog/open-source-retreat-2016
- https://www.gov.uk/tax-limited-company-gives-to-charity/sponsoring-a-charity

**Comment by wolftune** [comment] 2015-10-22 07:01
This already exists. It's [Software Freedom Conservancy](https://sfconservancy.org/). And that's the most notable one to be aware of, but there are several other more specific free software 501(c)(3)'s such as http://spi-inc.org/ — there's an entire community of related charities for free/open software already http://flossfoundations.org/ (I am a member per my in-progress non-profit startup [Snowdrift.coop](https://snowdrift.coop/) which is hoping to determine still whether 501(c)(3) is possible for us, but there may be conflicts with our general scope and particularly with our democratic governance and how that may not fit various (c)(3) rules, these things are complex).

The _first_ thing to assume about any idea is that it probably already exists or is being worked on.

Patreon is not related, it's not a charity, it's for-profit legally.

Micro-donations for bug fixes are not a new idea either, there's _ton_ of attempts at these things. Consider: https://snowdrift.coop/p/snowdrift/w/en/status-quo-floss and the complete list of existing platforms: https://snowdrift.coop/p/snowdrift/w/en/othercrowdfunding

Cheers

P.S. I'm actually getting involved here because I see a lot of attention to this issue, and I'm trying to help push all the folks who happened to congregate to this repo to get involved in existing initiatives. Many initiatives need help, there's lots of ways to make a difference. It's not like people otherwise have been oblivious to these things, solving the challenges is just a lot harder than identifying them. Apologies if I seem impatient or critical, I'm not wanting to discourage anyone. I just think coordination and cooperation are key here and have witnessed great numbers of people insisting on doing their own new thing only to waste time and energy oblivious to existing things and then die out after a few months.

**Comment by dferber90** [comment] 2015-10-22 07:06
Thanks for the reply. I imagined that to be a thing already, but I somehow was not able to find it. I tried searching for "open source charity" but that yielded mostly results of unrelated articles or a charity where the proceeds from selling software products can be donated.

Thanks for the links again :)

**Comment by dferber90** [comment] 2015-10-22 07:21
> Patreon is not related, it's not a charity, it's for-profit legally.

That's exactly why I put it there. It was meant as a "like this, but not-for-profit" example. 

> The _first_ thing to assume about any idea is that it probably already exists or is being worked on.

Don't want to get into a discussion here but dumping life advice like that just comes across as very arrogant. A lot of things exist already but are done in crappy ways. There's many examples where somebody did something that was already been done before, but in a significantly better way which leads to improving more peoples lives.

**Comment by wolftune** [comment] 2015-10-22 07:32
@dferber90 please accept my sincere apologies

I'm not being arrogant when I just clarify that arrogance is not the right interpretation (I'm not saying I'm better at interpreting text communication than you or anything, it's just easy to misinterpret and to mis-write the ideas in the first place). The correct interpretation is to recognize frustration. Frustration ≠ arrogance. I understand that in general it is possible that things done before are crappy and worth replacing. What I _don't_ like is the attitude I've seen from many people (but not from you, it's just a source of frustration generally) that doesn't feel a sense of burden to understand and learn about what already exists.

It's perfectly fine to be knowledgeable about what exists and decide thoughtfully that something new is warranted. I just deal with a lot of people (again, not saying this is you) who start out from the beginning assuming that something new is the answer, don't seek existing things, and when they learn about existing things, they say "oh, I see, but I already started my thing, so I'm going to keep working on it." Those folks are more interested in doing their own thing than in solving the problems we're all facing.

Now, you said you don't want to get into a discussion. Perhaps what you mostly mean is, you don't want me to be defensive, you don't have time or desire to hash out communication things… so, please accept my apology and my sincerity that I didn't mean to be condescending and I _do_ appreciate your feedback and graciousness. I just want us all to work together to solve these challenges. And, I'm biased, but I want folks here to come help with Snowdrift.coop as we've done our homework, understand the issues, and we're working on something that we know doesn't already exist, and we need help making it happen. So, please forgive my biases and such, I'll work to keep communicating as respectfully and productively as I can.

**Comment by dferber90** [comment] 2015-10-22 07:44
Thanks for explaining. It's all good 👍

**Comment by nayafia** [comment] 2015-10-23 13:09
Why'd you close this? It's a great idea!

The Software Freedom Conservancy does NOT provide funds to its member organizations. They provide legal infrastructure, nonprofit fiscal sponsorship, etc. It's a really important service, but it's not the same thing as what you originally proposed.

The idea of a centralized org providing unrestricted grants to developers to work on OSS projects actually does not yet exist. This is something I've been tinkering with and am very interested in exploring. 

It sounds like you're suggesting funding a couple of developers full-time to be a generalized "OSS contributor" and work on multiple projects; if so, https://rubytogether.org/ is good inspiration for that model.

I'm really interested in whether we could create an org to provide grants to developers to work on OSS projects in a less restricted format (i.e. they apply for a one-time grant with their own project), which can help support smaller projects and more flexibility.

LMK if you want to discuss further on here or offline, I'd love to get my ideas challenged on this too.

**Comment by wolftune** [comment] 2015-10-23 13:37
@nayafia Well, the SFC as a 501(c)(3) fiscal sponsor _does_ accept donations on behalf of the member projects. There are other foundations of various sorts (e.g. Shuttleworth Foundation) that provide grants people can apply for.

I certainly want to keep discussing this with you and others. You haven't replied to me on any of the threads where I've mentioned my organization already in progress ([Snowdrift.coop](https://snowdrift.coop/)). We are not precisely what you have in mind, but still… there's a lot of issues here. Your ideas remind me of Michael Fair's vision of a 501(c)(3) that is basically trusted to give grants to the most deserving projects, the idea being that donors don't have to worry about it, they trust the org to make the right decisions. It's not bad, but that on its own isn't going to change the donation patterns of people that much. You can already donate to existing large foundations, including ones that give generalized grants. I think those people who would like to just give to a trusted entity and not worry about it are _already_ confused about the best place to put their money, and adding even more organizations to the choices only amplifies that problem unless there's some reason it really stands out. Basically, I'm not convinced that there exists lots of people who are thinking "I have this money for FLOSS, I just don't know where to give it." I think we need a different way to convince people that giving is worthwhile in the first place.

**Comment by nayafia** [comment] 2015-10-23 14:02
@wolftune The question is how to fund FOSS, and there are very few orgs ponying up the capital in a meaningful way. That's what I'm here to learn and help figure out. SFC is a legal structure to facilitate donations, but your CFO != your investor. Shuttleworth funds "open everything" but doesn't consider FOSS to be, systemically, a hugely underfunded issue (they say so on their website), they're more interested in the general political implications of an open society. I have not yet found an org that provides meaningful capital (i.e. not beer money) to fund FOSS development. If you find one, I'd love to hear about it.

I'm glad you are working on Snowdrift and that you're energized about figuring this out. This repo exists to explore lots of ideas, however, and Snowdrift is just one approach. For example, I and several others on here take issue with developers themselves being the primary funders of FOSS, believing that there's a larger systemic issue at hand. You can hold a bake sale for your kid's school or you can lobby Congress for better funding for K-12 education. Neither approach is wrong; both are necessary. But there's no single panacea to any complex systemic issue, and we're all coming at this from different angles and experiences.

**Comment by wolftune** [comment] 2015-10-23 14:13
@nayafia Have you actually looked at what Snowdrift.coop is working to do? We are the _opposite_ of a developer-focused project. I'm a music teacher, not a programmer. Everything about Snowdrift.coop is about building a base of support from and focused on the interests of the general public in funding FLO projects that serve the public better, not just the interests of developers or funded by developers. Of _course_ I'm not saying we're the sole solution or anything like that, although we _do_ need help and are specifically working on things you and others seem interested in seeing succeed.

Anyway, there are many foundations. I'm not sure what you mean about "ponying up capital". Are you implying that SFC is stingy or something? The reason existing orgs aren't doing massive funding of FLO software is because the orgs are not fabulously wealthy. I remain skeptical that the issue is lack of orgs. The issue is lack of funds. SFC would do amazing things if we gave them a billion dollars. They are _not_ merely legal policy and account organization, their scope is much wider than that, but they are a small organization just scraping by. Same with SPI. One organization (that is 501(c)(6)) is doing farily well: the Linux Foundation. They fund development. There's a whole lot of similar orgs with particular scope. Most of them would happily fund development more if they only had more money.

I really am not trying to just be a nay-sayer, but I think your statement that SFC is not the org you envision is basically true only because you envision a far wealthier org. I don't think SFC's lack of being what you have in mind has anything to do with their legal scope, mission, structure… I think it has _only_ to do with the fact that getting a successful 501(c)(3) to raise substantial funds is extremely hard. And I have no reason to think some new org with a nearly duplicate mission would do better.

**Comment by nayafia** [comment] 2015-10-23 14:20
I got lazy with my language: by developers I meant essentially a citizen-funded model (developers being the obvious first community to draw from) instead of institutional funders (like companies).

Please don't make inflammatory assumptions (like that I'm implying the SFC is stingy). Of course, the larger issue for me is precisely that orgs like SFC are underfunded, not that SFC is the problem.

**Comment by wolftune** [comment] 2015-10-23 14:28
@nayafia I wasn't asserting that you were actually saying SFC was stingy, sorry for my wording (although I did use a `?`). I basically was challenging your dismissal of them as being not a fundraising org. You talk of them like they strictly _only_ do administrative assistance. But I'm pretty sure the reason they don't fund lots of development is only because they don't have the funds to.

Yes, I think getting companies to fund more is a good idea, but that's already where most of the funding comes from. And it creates conflicts of interest. We aren't going to achieve a future filled with freedom-respecting software if the funding of it is dependent on companies that mostly make proprietary software, and yet that's where almost all the money is today.

At any rate, we intend to develop some particular functions at Snowdrift.coop for _institutional_ patrons, although that isn't our MVP core focus immediately. Institutions face the snowdrift dilemma in similar ways as individuals.

**Comment by lovelydinosaur** [comment] 2015-10-23 14:52
Aside: Could we keep these a bit more positive :smile:

(@wolftune Given that there's been a couple of times in this thread where your tone has been unintentionally abrasive it might be worth being a little more mindful of wording, and keeping the conversation impersonal.)

**Comment by wolftune** [comment] 2015-10-23 14:54
@tomchristie thank you

**Comment by lovelydinosaur** [comment] 2015-10-23 14:58
:+1:

**Comment by nayafia** [comment] 2015-10-23 15:23
@tomchristie 😃

So exploring the charity idea: anyone have thoughts on funding full-time FOSS developers to work on various projects vs. funding the projects themselves? What's a better model for sustainability?

**Comment by dferber90** [comment] 2015-10-23 16:32
> Why'd you close this? It's a great idea!

@nayafia  Thank you :)

> It sounds like you're suggesting funding a couple of developers full-time to be a generalized "OSS contributor" and work on multiple projects;

I was thinking about giving to developers that want to reach certain milestones in specific projects, which they applied with. This way the charity can have a list of things accomplished through donations.

Regarding your suggestion: As Kent has put it, _"You contribute best to something you use regularly."_ [[1](https://medium.com/@kentcdodds/open-source-stamina-dafd063f9932#.llcruer88)]. That's why I think being a generalized "OSS contributor" may not be as appealing as finally having time to finish that thing you always wanted to get done on your own project.
Anyways, choosing how to spend the money seems like the nicest problem to have :)

Another thing is creating developer awareness for such programs. Actually letting people know they can get these funds. Again, the README-approach would work. Being a well-known charity amongst developers would make it more appealing for companies to donate.

> LMK if you want to discuss further on here or offline, I'd love to get my ideas challenged on this too.

This is basically almost everything I have on this 🙈 I posted to see where it goes from there.
I'm interested in your ideas though! :)

**Comment by nayafia** [comment] 2015-10-26 15:58
Yeah, I'm with you on giving to developers for specific milestones on specific projects. I wonder if a unifying theme (or picking 3-5 focus areas for grants) would help tell the story to donors. Ruby Together focuses on core Ruby dev tools for example. Might be more compelling than "funding OSS devs" generally.

I love the README idea for building awareness!

**Comment by ghost** [comment] 2015-11-30 12:59
Ive added to my README (Source Wikipedia):

**Charityware is a licensing model that supplies fully operational unrestricted software to the user and requests an optional donation be paid. The amount of donation may be left to the discretion of the user.**

¯|_(ツ)/¯

**Closed as completed** 2021-03-11 05:49 UTC
